### ISSUE TITLE
Error while running EDA-Peak-Detection-Script.py 

### ISSUE THREAD

**Issue by sukhadj** [MITMediaLabAffectiveComputing/eda-explorer#5]
I tried running the script for peak detection with e4 data type.
But got this error:

> 	Data Type (e4 or q or misc): e4
	Path to E4 directory: /home/sukhad/Workspace/FRICORP/sampleData/P01/S01/E02/2KNY3111DD/
Traceback (most recent call last):
  File "EDA-Peak-Detection-Script.py", line 205, in <module>
    data, filepath_confirm = getInputLoadFile()
  File "/home/sukhad/Workspace/FRICORP/eda-explorer/load_files.py", line 30, in getInputLoadFile
    data = loadData_E4(filepath)
  File "/home/sukhad/Workspace/FRICORP/eda-explorer/load_files.py", line 115, in loadData_E4
    eda_data = _loadSingleFile_E4(os.path.join(filepath,'EDA.csv'),["EDA"],4,"250L")
  File "/home/sukhad/Workspace/FRICORP/eda-explorer/load_files.py", line 103, in _loadSingleFile_E4
    data.columns = list_of_columns
  File "/home/sukhad/.local/lib/python3.5/site-packages/pandas/core/generic.py", line 3627, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/sukhad/.local/lib/python3.5/site-packages/pandas/core/generic.py", line 559, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/sukhad/.local/lib/python3.5/site-packages/pandas/core/internals.py", line 3074, in set_axis
    (old_len, new_len))
ValueError: Length mismatch: Expected axis has 2 elements, new values have 1 elements

My EDA.csv format is 
Unix Timetamp(UTC), eda(microS)

Thanks

**Comment by sukhadj** [comment]
The sample file format can be found 
[Q Sensor format](https://eda-explorer.media.mit.edu/static/sample_Q.csv)
[E4 format](https://eda-explorer.media.mit.edu/static/sample_E4.zip)

Hence closing this issue.

**Comment by gokhan-kazar** [comment]
Hi @sukhadj 
I am trying to load my EDA.csv file, but the path is not defined as below: 
Path to E4 directory: >? /Users/gokhankazar/Desktop/Veriler/E4/Wristband/5_Muhammed/Kurtuluş/EDA_Çarş.csv
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:/Users/gokhankazar/Desktop/eda-explorer-master/load_files.py", line 30, in getInputLoadFile
    data = loadData_E4(filepath)
  File "C:/Users/gokhankazar/Desktop/eda-explorer-master/load_files.py", line 119, in loadData_E4
    eda_data = _loadSingleFile_E4(os.path.join(filepath,'EDA.csv'),["EDA"],4,"250L")
  File "C:/Users/gokhankazar/Desktop/eda-explorer-master/load_files.py", line 98, in _loadSingleFile_E4
    data = pd.read_csv(filepath)
  File "C:\Users\gokhankazar\PycharmProjects\untitled1\venv\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\gokhankazar\PycharmProjects\untitled1\venv\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\gokhankazar\PycharmProjects\untitled1\venv\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\gokhankazar\PycharmProjects\untitled1\venv\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\gokhankazar\PycharmProjects\untitled1\venv\lib\site-packages\pandas\io\parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/Users/gokhankazar/Desktop/Veriler/E4/Wristband/5_Muhammed/Kurtulu\xc5\x9f/EDA_\xc3\x87ar\xc5\x9f.csv\\EDA.csv' does not exist: b'/Users/gokhankazar/Desktop/Veriler/E4/Wristband/5_Muhammed/Kurtulu\xc5\x9f/EDA_\xc3\x87ar\xc5\x9f.csv\\EDA.csv'

What should I do? Can you help me?

**Comment by sukhadj** [comment]
Hey @gokhan-kazar ,
You need to provide a directory path for E4 . Currently, you're giving it the path of EDA data file itself. Also, you need to have the files in a predefined format.
Find the format of file (sample files) here .

**Comment by sukhadj** [comment]
Hey @gokhan-kazar ,
You need to provide a directory path there.
Currently, you are providing path of EDA data file itself.
Also, you need to have those files in a predefined format (including name of those files).
Find sample files and format here: https://eda-explorer.media.mit.edu/static/sample_E4.zip

**Comment by gokhan-kazar** [comment]
Thanks @sukhadj 
I have some questions for EDA data cleaning process;
1)  When I put my file of directory path, I got the filtered data but also written message as below:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
This means that there is a problem for filtered data?
2) After load EDA, ACC and Temp file, I want to use getOutputPath() function to write filtered data, but it does not write in the directory path as file
3) Some functions (loadData_E4(filepath and _loadSingleFile_E4(filepath,list_of_columns, expected_sample_rate,freq))  need single E4 file, what is the differences between these functions and first filtering process that we use getInputLoadFile() function

thanks,
